# Site settings
name: Hou Zhicheng's Blog
title: Hou Zhicheng's Blog
email: zhichenghou@gmail.com
description: "Tech blog, interest in big data"
baseurl: 
url: "http://houzhicheng.com"
username: zhichenghou

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalinks: pretty
highlighter: rouge
